version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ~/data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf
